// Pomfret School Teachers and Staff
// Auto-generated from photo filenames in "Pomfret Teachers + Staff" folder
// Only includes teachers with existing photos

const allTeachers = [
  { name: "Paul Andrzejewski", photo: "./Pomfret Teachers + Staff/E_Andrzejewski_Paul.jpg" },
  { name: "Natalia Aragon", photo: "./Pomfret Teachers + Staff/E_Aragon_Natalia.jpg" },
  { name: "Patrick Boyd", photo: "./Pomfret Teachers + Staff/E_Boyd_Patrick.jpg" },
  { name: "Edward Browne", photo: "./Pomfret Teachers + Staff/E_Browne_Edward.jpg" },
  { name: "Ellen Browne", photo: "./Pomfret Teachers + Staff/E_Browne_Ellen.jpg" },
  { name: "Ryan Burns", photo: "./Pomfret Teachers + Staff/E_Burns_Ryan.jpg" },
  { name: "Mackenzie Christensen", photo: "./Pomfret Teachers + Staff/E_Christensen_Mackenzie.jpg" },
  { name: "Gwyneth Connell", photo: "./Pomfret Teachers + Staff/E_Connell_Gwyneth.jpg" },
  { name: "Brendan Daly", photo: "./Pomfret Teachers + Staff/E_Daly_Brendan.jpg" },
  { name: "Heather Daly", photo: "./Pomfret Teachers + Staff/E_Daly_Heather.jpg" },
  { name: "Tiffanie Deary", photo: "./Pomfret Teachers + Staff/E_Deary_Tiffanie.jpg" },
  { name: "Timothy Deary", photo: "./Pomfret Teachers + Staff/E_Deary_Timothy.jpg" },
  { name: "Victoria Dobbin", photo: "./Pomfret Teachers + Staff/E_Dobbin_Victoria.jpg" },
  { name: "Daniel Dunn", photo: "./Pomfret Teachers + Staff/E_Dunn_Daniel.jpg" },
  { name: "Brooke Feldman-Cryan", photo: "./Pomfret Teachers + Staff/E_Feldman-Cryan_Brooke.jpg" },
  { name: "Greg Fischer", photo: "./Pomfret Teachers + Staff/E_Fischer_Greg.jpg" },
  { name: "Erin Fisher", photo: "./Pomfret Teachers + Staff/E_Fisher_Erin.jpg" },
  { name: "Robert Fisher", photo: "./Pomfret Teachers + Staff/E_Fisher_Robert.jpg" },
  { name: "Gavin Flood", photo: "./Pomfret Teachers + Staff/E_Flood_Gavin.jpg" },
  { name: "Kathryn Fontaine", photo: "./Pomfret Teachers + Staff/E_Fontaine_Kathryn.jpg" },
  { name: "Kathleen Forrestal", photo: "./Pomfret Teachers + Staff/E_Forrestal_Kathleen.jpg" },
  { name: "Daniel Frejie", photo: "./Pomfret Teachers + Staff/E_Frejie_Daniel.jpg" },
  { name: "Sarah Gawronski", photo: "./Pomfret Teachers + Staff/E_Gawronski_Sarah.jpg" },
  { name: "Mary Georgis", photo: "./Pomfret Teachers + Staff/E_Georgis_Mary.jpg" },
  { name: "Brian Geyer", photo: "./Pomfret Teachers + Staff/E_Geyer_Brian.jpg" },
  { name: "Don Gibbs", photo: "./Pomfret Teachers + Staff/E_Gibbs_Don.jpg" },
  { name: "Matthew Goethals", photo: "./Pomfret Teachers + Staff/E_Goethals_Matthew.jpg" },
  { name: "William Harrington", photo: "./Pomfret Teachers + Staff/E_Harrington_William.jpg" },
  { name: "Jeremy Hatfield", photo: "./Pomfret Teachers + Staff/E_Hatfield_Jeremy.jpg" },
  { name: "Cooper Hemphill", photo: "./Pomfret Teachers + Staff/E_Hemphill_Cooper.jpg" },
  { name: "Arthur Horst", photo: "./Pomfret Teachers + Staff/E_Horst_Arthur.jpg" },
  { name: "Martha Horst", photo: "./Pomfret Teachers + Staff/E_Horst_Martha.jpg" },
  { name: "Elizabeth Jacquet", photo: "./Pomfret Teachers + Staff/E_Jacquet_Elizabeth.jpg" },
  { name: "Jean-Paul Jacquet", photo: "./Pomfret Teachers + Staff/E_Jacquet_JeanPaul.jpg" },
  { name: "Nina Joly", photo: "./Pomfret Teachers + Staff/E_Joly_Nina.jpg" },
  { name: "Louisa Jones", photo: "./Pomfret Teachers + Staff/E_Jones_Louisa.jpg" },
  { name: "Leslie Kendig", photo: "./Pomfret Teachers + Staff/E_Kendig_Leslie.jpg" },
  { name: "Joshua Lake", photo: "./Pomfret Teachers + Staff/E_Lake_Joshua.jpg" },
  { name: "Lindsay Lehmann", photo: "./Pomfret Teachers + Staff/E_Lehmann_Lindsay.jpg" },
  { name: "Douglas Litowitz", photo: "./Pomfret Teachers + Staff/E_Litowitz_Douglas.jpg" },
  { name: "Jackson Lyon", photo: "./Pomfret Teachers + Staff/E_Lyon_Jackson.jpg" },
  { name: "Karen Marshall", photo: "./Pomfret Teachers + Staff/E_Marshall_Karen.jpg" },
  { name: "Todd Matthew", photo: "./Pomfret Teachers + Staff/E_Matthew_Todd.jpg" },
  { name: "Coretta McCarter", photo: "./Pomfret Teachers + Staff/E_McCarter_Coretta.jpg" },
  { name: "Charlotte McMahon", photo: "./Pomfret Teachers + Staff/E_McMahon_Charlotte.jpg" },
  { name: "Pablo Montoro Alonso", photo: "./Pomfret Teachers + Staff/E_Montoro Alonso_Pablo.jpg" },
  { name: "Sean Murphy", photo: "./Pomfret Teachers + Staff/E_Murphy_Sean.jpg" },
  { name: "Tanya Nongera-Nickerson", photo: "./Pomfret Teachers + Staff/E_Nongera-Nickerson_Tanya.jpg" },
  { name: "Annie O'Sullivan", photo: "./Pomfret Teachers + Staff/E_OSullivan_Annie.jpg" },
  { name: "Sandra Pina de Stewart", photo: "./Pomfret Teachers + Staff/E_Pina de stewart_Sandra.jpg" },
  { name: "Gabriel Qua", photo: "./Pomfret Teachers + Staff/E_Qua_Gabriel.jpg" },
  { name: "Brian Rice", photo: "./Pomfret Teachers + Staff/E_Rice_Brian.jpg" },
  { name: "David Ring", photo: "./Pomfret Teachers + Staff/E_Ring_David.jpg" },
  { name: "Matthew Rodman", photo: "./Pomfret Teachers + Staff/E_Rodman_Matthew.jpg" },
  { name: "Benjamin Rosenberg", photo: "./Pomfret Teachers + Staff/E_Rosenberg_Benjamin.jpg" },
  { name: "Dylan Ernst Schafer", photo: "./Pomfret Teachers + Staff/E_Schafer_Dylan Ernst.jpg" },
  { name: "Collin Shapiro", photo: "./Pomfret Teachers + Staff/E_Shapiro_Collin.jpg" },
  { name: "Sydney Stith", photo: "./Pomfret Teachers + Staff/E_Stith_Sydney.jpg" },
  { name: "Amy VanHoesen", photo: "./Pomfret Teachers + Staff/E_VanHoesen_Amy.jpg" },
  { name: "Stephen VanHoesen", photo: "./Pomfret Teachers + Staff/E_VanHoesen_Stephen.jpg" },
  { name: "Michaela Vitagliano", photo: "./Pomfret Teachers + Staff/E_Vitagliano_Michaela.jpg" },
  { name: "Kevin Vlasseman", photo: "./Pomfret Teachers + Staff/E_Vlasseman_Kevin.jpg" },
  { name: "Alyssa Walker", photo: "./Pomfret Teachers + Staff/E_Walker_Alyssa.jpg" },
  { name: "Michael Waller", photo: "./Pomfret Teachers + Staff/E_Waller_Michael.jpg" },
  { name: "Caroline Wardlow", photo: "./Pomfret Teachers + Staff/E_Wardlow_Caroline.jpg" },
  { name: "Amber Wildes", photo: "./Pomfret Teachers + Staff/E_Wildes_Amber.jpg" },
  { name: "Joshua Wildes", photo: "./Pomfret Teachers + Staff/E_Wildes_Joshua.jpg" },
  { name: "Bennett Wilson", photo: "./Pomfret Teachers + Staff/E_Wilson_Bennett.jpg" },
  { name: "Nicole Wilson", photo: "./Pomfret Teachers + Staff/E_Wilson_Nicole.jpg" },
  { name: "Maegan Windus", photo: "./Pomfret Teachers + Staff/E_Windus_Maegan.jpg" },
  { name: "Bruce Wolanin", photo: "./Pomfret Teachers + Staff/E_Wolanin_Bruce.jpg" }
];
